### ISSUE TITLE
CHIRPS registration support

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#106]
This issue is to update the [CHIRPS model run script](https://github.com/jataware/dojo/blob/master/models/chirps/run_chirps_tiff.py) to only support monthly requests for CHIRPS and CHIRPS-GEFS.

We should work with UCSB to ensure we are doing this correctly, but the general idea is that the user would request a month, hear and product (CHIRPS or CHIRPS-GEFS) and get all statistics for the entire month.

CHIRPS-GEFS is a forward looking 15 day forecast: if you request if for 10/29/2021 it covers 10/29 through 11/14). So it needs to be treated specially. If the user asks for October we'd pull 10/1 and 10/15 (confirm with UCSB) and combine them. If they request October but _it's only 10/14_ I'm not sure what we should do.

For both products all available stats should be pulled and combined into a single CSV (data, anomalies, and SPI).

**Comment by brandomr** [comment]
For CHIRPS-GEFS we could also do something more complicated by averaging the forecast from all 31 days of the month or something like that...

**Comment by GoogleSheets** [comment]
@brandomr It will create a CSV like this:
```
band	y	x	Rainfall	date	Avg-Rainfall	SPI
1	16.48	33.54	0.00	1/1/2020	0.00E+00	0
1	16.48	33.89	0.00	1/1/2020	0.00E+00	0
1	16.48	33.94	0.00	1/1/2020	0.00E+00	0
1	16.48	33.99	0.00	1/1/2020	0.00E+00	0
1	16.48	34.93	0.00	1/1/2020	0.00E+00	0
1	16.48	34.98	0.00	1/1/2020	0.00E+00	0
1	16.48	35.03	0.16	1/1/2020	6.92E-03	0
1	16.48	35.08	0.17	1/1/2020	6.29E-03	0
1	16.48	35.13	0.18	1/1/2020	4.44E-03	0
1	16.48	35.18	0.19	1/1/2020	4.79E-03	0
1	16.48	35.23	0.21	1/1/2020	5.06E-03	0
1	16.48	35.28	0.22	1/1/2020	4.81E-04	0
1	16.48	35.33	0.22	1/1/2020	2.23E-04	0
1	16.48	35.38	0.22	1/1/2020	2.29E-04	0
1	16.48	35.43	0.22	1/1/2020	1.22E-04	0
1	16.48	35.48	0.22	1/1/2020	1.36E-04	0
```
Do we want the column names to be 'data', 'anomali', 'spi' instead of [rainfall, Avg-Rainfall, SPI], nuke the band column, and reorder the columns; or just leave as is?

Next step is the GEFS.

**Comment by mlandsfeld** [comment]
I would go with Anomaly instead a Avg-rainfall. And the EWX Geoserver uses z-score instead of SPI. But I don't think that matters to WMers.

Here is a test script that builds the URL for retrieving CHIRPS-GEFS. It prints a curl command at the end for easy testing. I have one for LST as well...



#=========  CHIRPS-GEFS ======================

stat = 'anomaly' # 'data ''anomaly' 'z-score'
year = 2021
doy = 299
min_pt = [-2128992.283, -4214602.306]
max_pt = [5858710.218, 4615766.178]


if stat == 'data':
    units = 'mm'

if stat == 'anomaly':
    units = 'mm'

if stat == 'z-score':
    units = 'none'

url = f"https://chc-ewx2.chc.ucsb.edu/proxies/wcsProxy.php?layerNameToUse=chirpsgefs15day2:"\
      f"chirpsgefs15day2_africa_1-day-{doy}-{year}_{units}_{stat}"\
      f"&lowerLeftXToUse={min_pt[0]}&lowerLeftYToUse={min_pt[1]}"\
      f"&upperRightXToUse={max_pt[0]}&upperRightYToUse={max_pt[1]}"\
      f"&wcsURLToUse=https://chc-ewx2.chc.ucsb.edu:8443/geoserver/wcs?"\
      f"&resolution=0.05&srsToUse=EPSG:3857&outputSrsToUse=EPSG:4326"


print("curl '" + url + "' > ~/tmp/cg.tiff")
