### ISSUE TITLE
Get latest models returns multiple versions for each model

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#120]
Seems to be a bug in [this code](https://github.com/jataware/dojo/blob/master/api/src/models.py#L50-L80)

**Comment by hartleybrody** [comment]
I'm going to assign then to @BecketTrotter since he seems to have figured it out [in this slack thread](https://jataware.slack.com/archives/CAZTFECQY/p1636565421361700):

https://github.com/jataware/dojo/commit/6fb41560c2d0e21bfa6b16cfc7a0d0cbc62f011b#diff-621c6dd59ff1b35ccf4d073f7dc9b373601dde24323be89f873575c64f4cdfe8L180

He'd probably have a better sense of what the fix should be.
