### ISSUE TITLE
CHIRPS runs fail in Causemos

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#139]
The 3 CHIRPS models fail in Causemos with the default parameters:

https://causemos.uncharted.software/#/model/27f02b13-e60f-4bd3-b963-2ba0d67857be/model-publishing-experiment?datacube_id=a14ccbdf-c8d5-4816-af52-8b2ef3da9d22

https://causemos.uncharted.software/#/model/27f02b13-e60f-4bd3-b963-2ba0d67857be/model-publishing-experiment?datacube_id=7b2ed84f-d5f6-4b37-87bd-47b928d35f1f

https://causemos.uncharted.software/#/model/27f02b13-e60f-4bd3-b963-2ba0d67857be/model-publishing-experiment?datacube_id=0d6d8dfa-0f99-4b1f-8530-25ff5213d6e6

The errors are basically the same:

```
rasterio.errors.RasterioIOError: 'results/chirps-mm_data.tiff' not recognized as a supported file format.
```

For example, for run `c54c06b3-3ca4-4218-bdca-66a6fd9e2602` the logs are available at /home/ubuntu/dmc/results/c54c06b3-3ca4-4218-bdca-66a6fd9e2602/ddd12a2c-2939-44f6-91e1-6d6146752b8a

Here is a zipfile of `chirps-mm_data.tiff` from that run:

[chirps-mm_data.tiff.zip](https://github.com/jataware/dojo/files/7613764/chirps-mm_data.tiff.zip)

**Comment by GoogleSheets** [comment]
The contents of chirps_mm_data.tiff are:
`Error:Failed to connect to chc-ewx2.chc.ucsb.edu port 8443: Connection refused`

The usual test parameters for CHIRPS produces the following URL: 

`https://chc-ewx2.chc.ucsb.edu/proxies/wcsProxy.php?layerNameToUse=chirps:chirps_africa_1-month-01-2021_mm_data&lowerLeftXToUse=3730564.8242250294&lowerLeftYToUse=302892.4463571922&upperRightXToUse=5563938.50617707&upperRightYToUse=1862904.138846891&wcsURLToUse=https://chc-ewx2.chc.ucsb.edu:8443/geoserver/wcs?&resolution=0.05&srsToUse=EPSG:3857&outputSrsToUse=EPSG:4326`

That also results in the `Connection: refused` error. This suggests an issue the endpoint, unless an error was introduced into the URL construction since earlier success.

**Comment by GoogleSheets** [comment]
@brandomr It looks like this was due to server error at ucsb.edu. What is the best way to test this in CauseMos?

**Comment by brandomr** [comment]
@GoogleSheets as far as I can tell they are working. I requested a new run https://causemos.uncharted.software/#/model/27f02b13-e60f-4bd3-b963-2ba0d67857be/model-publishing-experiment?datacube_id=7b2ed84f-d5f6-4b37-87bd-47b928d35f1f and it is now "processing". This a few hours ago but it succeeded on our end.
