### ISSUE TITLE
Date Data Annotation

### ISSUE THREAD

**Issue by GoogleSheets** [jataware/dojo-deprecated#32]
This issue is meant to clarify and address the data annotation step of Date fields, in particular the annotation of the date used as `primary_time`.

Summary

- MixMasta outputs a single timestamp field based on the detection of a date field annotated as `primary_time` = **true**.
- Therefore, there should be only one data field of `Time` type `Date` set as `primary_time`. 
- If no data field is annotated to `Time` type `Date` and set as `primary_time`, then data fields of `Time` type `Month`, `Day`, and `Year` may be set as `primary_time` Only one of each type (`Month`, `Day`, `Year`) should be set as `primary_time`.

Questions

Is it possible to do the following:
- add a logic check to dojo form submission to enforce the `primary_time` rules specified above?
- default Year field data annotation to `Time:` **`Year`** and (**unchecked**) `This is my primary time field` instead of the current defaults of `Time:` **`Date`** and (**checked**) `This is my primary time field`?
- do the same with `Month` and `Day` as for `Year`.

Notes

- MixMasta will handle string month to numeral conversions e.g. June to 6.

**Comment by brandomr** [comment]
@marshHawk4 @BecketTrotter see above. 

@marshHawk4 this relates to our discussion today on how we want to handle time in Spacetag. For example, let's say the data looks like this:

| Year | Mo |
|------|-------|
| 2020 | Aug   |
| 2021 | Jun   |
| 2022 | Jan   |

Should `Mo` column be categorized as `Date/Time` with the string formatter `%b`? Or should it be categorized as `Month`? What is more intuitive to the user?

If we have an option for category `Month` and categorize the `Mo` column as `Month`, we DO need to know that it is `%b` so that we are able to use it in an epoch conversion in Mixmasta by @GoogleSheets. 

I propose we each think about how this might work best from a UX perspective and then sync up for a brief conversation later this week to make a decision.
